package plugins.mBurda.filters;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

import org.jdesktop.swingx.image.GaussianBlurFilter;

import icy.image.IcyBufferedImage;
import icy.image.colormodel.IcyColorModel;
import icy.sequence.Sequence;
import icy.type.DataType;
import plugins.adufour.ezplug.*;

public class CurvilinearStructures extends EzPlug {

	Vesselness2D ves = null;
	Neuriteness2D neu = null;
	
	
	EzVarInteger blur = new EzVarInteger("Radius of blur",1,0,10,1);
	EzVarBoolean vesselness = new EzVarBoolean("Compute Vesselness?",false);
	EzVarBoolean neuriteness = new EzVarBoolean("Compute neuriteness?",false);
	EzVarDouble betaThreshold =new EzVarDouble("Disparsity control",0,-50,50,0.05);
	EzVarDouble gammaThreshold = new EzVarDouble("Relative brightness control",0,-5,5,0.02);
	EzVarDouble alphaSteer = new EzVarDouble("Steerable filter equivalent",0,-50,50,0.05);
	EzVarDouble cutoffValue = new EzVarDouble("Cutoff value",0,-100,100,1);
	EzVarDouble threshold = new EzVarDouble("Threshold",0,-100,100,1);
	EzVarDouble gainFactor = new EzVarDouble("Gain factor",0,-50,50,0.05);
	EzVarBoolean vesPhase = new EzVarBoolean("Compute vesselness with phase congruency?",false);
	EzVarBoolean neuPhase = new EzVarBoolean("Compute neuriteness with phase congruency?",false);
	EzVarInteger angleKernels = new EzVarInteger("Number of kernels for angle computation.",2,2,8,2);
	
	EzGroup vesGroup = new EzGroup("Vesselness",betaThreshold,gammaThreshold);
	EzGroup neuGroup = new EzGroup("Neuriteness",alphaSteer);
	EzGroup phaseCongGroup = new EzGroup("Phase congruency parameters",threshold,cutoffValue,gainFactor);
	EzGroup outputGroup = new EzGroup("Show output",vesselness,vesPhase,neuriteness,neuPhase);
	EzGroup angleGroup = new EzGroup("Angle parametrization",angleKernels);
	
	@Override
	protected void initialize() {
		addEzComponent(blur);
		addEzComponent(outputGroup);
		addEzComponent(vesGroup);
		addEzComponent(neuGroup);
		addEzComponent(phaseCongGroup);
		addEzComponent(angleGroup);
	}

	@Override
	protected void execute() {
		GaussianBlurFilter gauss = new GaussianBlurFilter(blur.getValue());
		BufferedImage img = getGrayScale(gauss.filter(getActiveImage(), null));
		double[] scs = {0.015,0.02,0.05,0.09,0.13};
		
		double[] ors = {angleKernels.getValue()};
		{
			int tmp = 2;
			for(int i=2;i<angleKernels.getValue();i*=2){
				tmp=i;
			}
			ors = new double[tmp];
		}
		for(int i=0;i<ors.length;i++){
			ors[i] = i*(180/ors.length)*(Math.PI/180);
		}
		
		if(vesselness.getValue()){
			ves = new Vesselness2D(img, betaThreshold.getValue(), (gammaThreshold.getValue()));
			addSequence(new Sequence("Vesselness",ves.makeImage2D()));
		}
		if(vesPhase.getValue()){
			if(ves == null) ves = new Vesselness2D(img, betaThreshold.getValue(), gammaThreshold.getValue());
			Filter.phaseCong = Computations.getPhaseCong(Computations.FourierTransform2D(Filter.source, false), 
					scs, ors, threshold.getValue(), cutoffValue.getValue(), gainFactor.getValue());
			addSequence(new Sequence("Vesslness with phase congurency",ves.makeImageWithPhase2D()));
		}
		if(neuriteness.getValue()){
			neu = new Neuriteness2D(img, alphaSteer.getValue());
			addSequence(new Sequence("Neuriteness",neu.makeImage2D()));
		}
		if(neuPhase.getValue()){
			if(neu == null) neu = new Neuriteness2D(img, alphaSteer.getValue());
			if(!vesPhase.getValue()) Filter.phaseCong = Computations.getPhaseCong(Computations.FourierTransform2D(Filter.source, false), 
					scs, ors, threshold.getValue(), cutoffValue.getValue(), gainFactor.getValue());
			addSequence(new Sequence("Neuriteness",neu.makeImageWithPhase2D()));
		}
		
//		addSequence(new Sequence("Gabor",getImage()));
	}
	
//	private IcyBufferedImage getImage(){
////		IcyBufferedImage ret = new IcyBufferedImage(Filter.phaseCong[0].length, Filter.phaseCong.length, IcyColorModel.createInstance(1, DataType.DOUBLE));
//		IcyBufferedImage ret = new IcyBufferedImage(200, 200, IcyColorModel.createInstance(1, DataType.DOUBLE));
//		ret.beginUpdate();
//		double[][] dob = Computations.getGaborKernel2D(200, 200, 0.13, 90, 0.75, 3);
//		for(int y=0;y<200;y++){
//			for(int x=0;x<200;x++){
//				ret.setDataAsDouble(x, y, 0, dob[x][y]);
//			}
//		}
//		ret.endUpdate();
//		return ret;
//	}
	
	@Override
	public void clean() {
		// TODO Auto-generated by Icy4Eclipse
	}
	
	private BufferedImage getGrayScale(BufferedImage original){
		BufferedImage image = new BufferedImage(original.getWidth(), original.getHeight(),
				BufferedImage.TYPE_BYTE_GRAY);  
		Graphics g = image.getGraphics();
		g.drawImage(original, 0, 0, null);
		g.dispose(); 
		return image;
	}
	
	public static void runOnSpecPars(BufferedImage input,int blur,double disparsity,double brightness,int threshold,double cutoff,double gainFactor) throws IOException{
		double[] scs = {0.0015,0.002,0.005,0.009,0.013};
		double[] ors = {4};
		for(int i=0;i<ors.length;i++){
			ors[i] = i*(180/ors.length)*(Math.PI/180);
		}
		GaussianBlurFilter gauss = new GaussianBlurFilter(blur);
		BufferedImage img = gauss.filter(input, null);
		
		Vesselness2D ves = new Vesselness2D(img);
		
		Filter.phaseCong = Computations.getPhaseCong(Computations.FourierTransform2D(img, false), scs, ors, threshold, cutoff, gainFactor);
		img = ves.makeImageWithPhase2D();
		File f = new File("/home/marek/Images/Img_"+ disparsity +"_"+ brightness+"_"+ cutoff +"_"+gainFactor+".png");
		ImageIO.write(img, "PNG", f);
	}
}
