package plugins.mBurda.filters;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import icy.gui.frame.sequence.SequenceActionFrame;
import icy.gui.dialog.MessageDialog;
import icy.plugin.abstract_.PluginActionable;
import icy.sequence.Sequence;
import icy.image.IcyBufferedImage;

public class Filters extends PluginActionable {
//	private int choiceOfFilter = -1;
//	private javax.swing.JLabel label;
//	private javax.swing.JComboBox jComboBox1; 
//	
//	@Override
//	public void run() {
//		label.setText("Choose filter");
//		final SequenceActionFrame mainFrame = new SequenceActionFrame("Set parameters of filters", true);
//		mainFrame.setOkAction(new ActionListener()
//        {
//            @Override
//            public void actionPerformed(ActionEvent e)
//            {
//            	//int choiceOfFilter = -1;
//
//            	final Sequence sequence = mainFrame.getSequence();
//                
//                if (sequence == null){
//                    MessageDialog.showDialog("No sequence selected");
//                    return;
//                }
//                switch (choiceOfFilter) {
//				case 0:
//					Vesselness ves = new Vesselness(getActiveSequence().getImage(0, 0), 30);
//					ves.makeImage2D();
//					addSequence(new Sequence(ves.ret));
//					break;
//				case 1:
//					Neuriteness neu = new Neuriteness(getActiveSequence().getImage(0, 0), 30);
//					neu.makeImage2D();
//					addSequence(new Sequence(neu.ret));
//					break;
//				default:
//					MessageDialog.showDialog("No filter selected");
//					break;
//				}
//            }
//        });
//		
//		mainFrame.setCloseAfterAction(false);
//		addIcyFrame(mainFrame);
//        mainFrame.center();
//        // make it visible
//        mainFrame.setVisible(true);
//        // and get focus
//        mainFrame.requestFocus();
	public void run() {
		Vesselness ves = new Vesselness(getActiveSequence().getImage(0, 0), 30);
		ves.makeImage2D();
		addSequence(new Sequence(ves.ret));
		Neuriteness neu = new Neuriteness(getActiveSequence().getImage(0, 0), 30);
		neu.makeImage2D();
		addSequence(new Sequence(neu.ret));
	
		// TODO Auto-generated by Icy4Eclipse
		MessageDialog.showDialog("Filt is done !");
	}

}
