package plugins.mBurda.filters;

import icy.gui.dialog.MessageDialog;
//import icy.image.IcyBufferedImage;
import icy.plugin.abstract_.PluginActionable;
import icy.sequence.Sequence;

public class Filters extends PluginActionable {

	@Override
	public void run() {

		Vesselness ves = new Vesselness(getActiveSequence().getImage(0, 0), 30);
		ves.makeImage();
		addSequence(new Sequence(ves.ret));
		// TODO Auto-generated by Icy4Eclipse
		MessageDialog.showDialog("Filt is done !");
	}

}
