package plugins.mBurda.filters;


import icy.gui.dialog.MessageDialog;
import icy.plugin.abstract_.PluginActionable;
import icy.sequence.Sequence;

public class Filters extends PluginActionable {
	@Override
	public void run() {

////		MainWindow main = new MainWindow();
////		main.setVisible(true);

//                switch (choiceOfFilter) {
//				case 0:
					Vesselness ves = new Vesselness(getActiveSequence().getImage(0, 0), 50,1,0.75);
					ves.makeImage2D();
					addSequence(new Sequence(ves.ret));
//					break;
//				case 1:
//					Neuriteness neu = new Neuriteness(getActiveSequence().getImage(0, 0), 30,3);
//					neu.makeImage2D();
//					addSequence(new Sequence(neu.ret));
//					break;

		// TODO Auto-generated by Icy4Eclipse
		//MessageDialog.showDialog("Filt is done !");
	}

}
