package plugins.mBurda.filters;

import icy.gui.dialog.MessageDialog;
import plugins.adufour.*;

public class GUI extends EzPlug {

	@Override
	protected void initialize() {
		// TODO Auto-generated by Icy4Eclipse
	}

	@Override
	protected void execute() {
		// TODO Auto-generated by Icy4Eclipse
		MessageDialog.showDialog("phaseCong is working fine !");
	}

	@Override
	public void clean() {
		// TODO Auto-generated by Icy4Eclipse
	}
}}